version: "3.9"
services:
  vedge:
    build: vedge
    # restart: always
    environment:
      CONFIG_PATH: config.yaml
      LOG_LEVEL: "debug"

  agent:
    build: agent
    depends_on:
      - vedge
    links:
      - vedge
    volumes:
      - ./weights:/etc/weights
    # restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      ENV_ADDRESS: vedge
      ENV_PORT: 80
      LOG_LEVEL: "debug"

  task-generator:
    build: task-generator
    depends_on:
      - agent
    links:
      - agent
    # restart: always
    environment:
      LAMBDA: 0.1
      SPEED: 10
      AGENT_ADDRESS: agent
      AGENT_PORT: 80
      LOG_LEVEL: "debug"
