version: "3.9"
services:
  vedge:
    build: vedge
    environment:
      CONFIG_PATH: config.yaml
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    # restart: always

  agent:
    build: agent
    depends_on:
      - vedge
    links:
      - vedge
    volumes:
      - ./weights:/etc/weights
      - ./logs:/etc/logs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      ENV_ADDRESS: vedge
      ENV_PORT: 80
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    # restart: always

  task-generator:
    build: task-generator
    depends_on:
      - agent
    links:
      - agent
    environment:
      LAMBDA: 0.1
      SPEED: 10
      AGENT_ADDRESS: agent
      AGENT_PORT: 80
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    # restart: always
